[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "xfel"
version = "0.1"
dependencies = [
    "scikit-learn",
    "jinja2"
]

[project.scripts]
"cctbx.xfel.merge" = "xfel.merging.command_line.merge:main"
"cctbx.xfel.itermerge" = "scripts.iter_merge:main"
"cctbx.xfel.cc12" = "scripts.merge_log_cc12:main"
"cctbx.xfel.detector_residuals" = "xfel.command_line.detector_residuals:main" 

